# Generated by Django 5.1.4 on 2024-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('kegiatan', 'Kegiatan'), ('prestasi', 'Prestasi'), ('fasilitas', 'Fasilitas'), ('lainnya', 'Lainnya')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Galeri',
                'ordering': ['-tanggal'],
            },
        ),
    ]
