# Generated by Django 5.1.4 on 2024-12-10 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(max_length=100)),
                ('nama_mapel', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guru', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guru',
            },
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'karyawan',
            },
        ),
        migrations.CreateModel(
            name='siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_siswa', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'siswa',
            },
        ),
    ]
